name: terraform-eks

on:
  workflow_dispatch:
    inputs:
      target_env:
        description: "Ambiente (dev|stage)"
        required: true
        default: "dev"
  push:
    branches: ["main"]

permissions:
  contents: read
  id-token: write

jobs:
  apply:
    runs-on: ubuntu-latest

    # stage quando push su main, altrimenti usa input
    environment: ${{ github.event_name == 'push' && 'stage' || inputs.target_env }}

    # evita 2 apply contemporanei sullo stesso state (dev/stage)
    concurrency:
      group: tfstate-eks-${{ github.event_name == 'push' && 'stage' || inputs.target_env }}
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v4

      - name: Select role/env
        id: sel
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            echo "env=stage" >> $GITHUB_OUTPUT
            echo "role=${{ secrets.AWS_ROLE_EKS_STAGE }}" >> $GITHUB_OUTPUT
          else
            if [ "${{ inputs.target_env }}" = "stage" ]; then
              echo "env=stage" >> $GITHUB_OUTPUT
              echo "role=${{ secrets.AWS_ROLE_EKS_STAGE }}" >> $GITHUB_OUTPUT
            else
              echo "env=dev" >> $GITHUB_OUTPUT
              echo "role=${{ secrets.AWS_ROLE_EKS_DEV }}" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ steps.sel.outputs.role }}
          aws-region: eu-central-1

      - name: Verify identity
        run: aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform/eks
        run: |
          terraform init \
            -backend-config="bucket=${TFSTATE_BUCKET}" \
            -backend-config="dynamodb_table=${TFLOCK_TABLE}" \
            -backend-config="key=eks/${{ steps.sel.outputs.env }}/terraform.tfstate" \
            -backend-config="region=eu-central-1"
        env:
          TFSTATE_BUCKET: ${{ secrets.TFSTATE_BUCKET }}
          TFLOCK_TABLE:  ${{ secrets.TFLOCK_TABLE }}

      - name: Terraform Apply
        working-directory: terraform/eks
        run: |
          terraform apply -lock-timeout=10m -input=false -auto-approve \
            -var="cluster_name=eks-lab-${{ steps.sel.outputs.env }}"
        env:
          TF_VAR_region: eu-central-1
          TF_VAR_vpc_id:             ${{ secrets.VPC_ID }}
          TF_VAR_private_subnet_ids: ${{ secrets.PRIVATE_SUBNET_IDS }}
          TF_VAR_public_subnet_ids:  ${{ secrets.PUBLIC_SUBNET_IDS }}
          TF_VAR_my_ip_cidr:         ${{ secrets.MY_IP_CIDR }}
